I've changed the function of the log in page, that everytime the user…
ivan-clark/portfolio pull request #18
Opened 2023-11-13 16:59 UTC by sulfur132

… is trying to log in, the button will load, so that the user will not be confused if the user is logged in or not.

2023-11-18 21:33 UTC, ivan-clark requested changes

2023-11-18 21:33 UTC, ivan-clark commented on frontend/src/pages/Register.jsx
> +        password,
nagka baylo ang order sa mga parameters: maong inig ka register ang firstname nahimong username then ang lastname nahimong password

2023-11-18 21:36 UTC, ivan-clark requested changes

2023-11-18 21:36 UTC, ivan-clark commented on frontend/src/pages/Register.jsx
> +        password,
Then ang usage ani is only: `Api.register(firstname, lastname, username, password)`

no need na ni ```
{
        firstname,
        lastname,
        username,
        password,
}
```

2023-11-18 22:37 UTC, sulfur132 commented on frontend/src/pages/Register.jsx
> +        password,
Already Fixed sirs.

2023-11-19 12:15 UTC, ivan-clark approved these changes
nice!

2023-11-19 12:16 UTC, merged